export type ArchiveProject = {
  title: string;
  overview: string;
  benefit: string;
  uniqueness: string;
  stack: string[];
  deliverables: string[];
};

export const projectArchive: Record<string, ArchiveProject[]> = {
  "COMPUTER VISION": [
    { title:"Automated Defect Detection", overview:"A real-time visual inspection pipeline that analyzes manufactured parts in motion and identifies surface scratches, missing components and soldering irregularities before they leave the line.", benefit:"Reduces manual inspection load, catches repeatable quality issues earlier and creates traceable evidence for process improvement.", uniqueness:"Combines controlled image acquisition, augmentation for rare defects and confidence-aware classification instead of relying on a single clean laboratory dataset.", stack:["OpenCV","CNN","Python","Data Augmentation"], deliverables:["Conveyor-frame capture and region-of-interest pipeline","Defect classifier with augmented training workflow","Operator-ready pass/fail output with confidence evidence"] },
    { title:"Face Mask & PPE Compliance", overview:"A live safety-monitoring system that detects people and verifies hard-hat and mask compliance inside restricted industrial zones.", benefit:"Helps safety teams identify non-compliance quickly without continuously watching multiple video feeds.", uniqueness:"Treats compliance as a person-level association problem, linking each detected worker with the correct PPE detections across changing poses and partial occlusion.", stack:["YOLO","OpenCV","Bounding Boxes","Video Processing"], deliverables:["Multi-class worker and PPE detection model","Real-time annotated monitoring feed","Zone-aware compliance alerts and event records"] },
    { title:"Smart Checkout / Retail Analytics", overview:"A camera-driven retail system that detects, classifies and tracks products placed on a checkout surface to build a live basket without barcode scanning.", benefit:"Reduces checkout friction while producing item-level interaction data useful for store operations and inventory analysis.", uniqueness:"Maintains object identity across hand occlusion and item overlap, preventing duplicate billing when products move within the scene.", stack:["Object Tracking","Multi-class CNN","OpenCV","Retail Analytics"], deliverables:["Product detection and classification pipeline","Persistent track IDs and basket-state engine","Live billing interface with add/remove reconciliation"] },
    { title:"Number Plate Recognition & Tolling", overview:"An automatic number-plate recognition pipeline that localizes vehicle plates, normalizes difficult captures and extracts registration text for parking or toll workflows.", benefit:"Speeds vehicle entry, reduces manual transcription and creates searchable movement records.", uniqueness:"Uses plate-specific perspective correction, illumination normalization and OCR validation to handle angled vehicles and inconsistent lighting.", stack:["Tesseract OCR","OpenCV","Image Preprocessing","Python"], deliverables:["Vehicle and plate localization stages","Perspective correction and OCR-ready preprocessing","Validated plate text API and tolling event output"] },
    { title:"Interactive Hand Gesture Controller", overview:"A touch-free control interface that converts hand landmarks and gestures from a standard webcam into commands for volume, presentations and connected devices.", benefit:"Enables accessible, hygienic and intuitive control where a keyboard, remote or touch surface is inconvenient.", uniqueness:"Separates continuous controls such as volume from discrete gesture commands using temporal smoothing and gesture-state rules.", stack:["MediaPipe","Python","HCI","Landmark Tracking"], deliverables:["Real-time hand landmark and gesture recognizer","Debounced command mapping and smoothing engine","Desktop and presentation-control integrations"] },
    { title:"Medical Image Screening", overview:"A research-oriented screening prototype that segments suspicious regions in X-ray or MRI imagery and presents visual overlays for expert review.", benefit:"Supports faster prioritization and gives clinicians or researchers an interpretable area-of-interest map alongside the source scan.", uniqueness:"Uses segmentation rather than only returning a label, preserving spatial evidence for review. It is explicitly a research aid, not a diagnostic device.", stack:["U-Net","PyTorch","Segmentation","Medical Imaging"], deliverables:["Medical-image normalization and dataset pipeline","U-Net segmentation training and validation workflow","Overlay viewer with region-level confidence visualization"] },
    { title:"Agricultural Crop Disease Detector", overview:"A leaf-image analysis system that classifies crop disease patterns and surfaces targeted treatment guidance suitable for a mobile workflow.", benefit:"Helps growers recognize plant stress earlier and focus treatment instead of applying broad, unnecessary intervention.", uniqueness:"Pairs transfer learning with lightweight inference and confidence-aware recommendations for field conditions where images are rarely studio-perfect.", stack:["Transfer Learning","TensorFlow","Mobile Deployment","Classification"], deliverables:["Leaf capture and background-normalization flow","Disease classification model with confidence ranking","Mobile-ready result and localized guidance interface"] },
  ],
  "MACHINE LEARNING": [
    { title:"Customer Churn Prediction", overview:"A supervised risk-scoring system that predicts which telecom or SaaS customers are most likely to cancel using behavior, tenure and usage signals.", benefit:"Allows retention teams to focus outreach and incentives on customers where intervention has the highest potential value.", uniqueness:"Optimizes for the asymmetric cost of missed churn rather than headline accuracy, with interpretable drivers for each prediction.", stack:["XGBoost","Feature Engineering","SHAP","Imbalanced Learning"], deliverables:["Reusable feature and data-quality pipeline","Calibrated churn-risk model and threshold analysis","SHAP explanations and retention-priority dashboard"] },
    { title:"Dynamic Real Estate Price Predictor", overview:"A multi-variable valuation model using location, size, amenities and comparable properties to estimate a realistic price range.", benefit:"Improves pricing consistency for buyers, sellers and agents while exposing the features that materially affect valuation.", uniqueness:"Presents uncertainty and SHAP-based drivers instead of hiding the decision behind one unexplained number.", stack:["Regression","XGBoost","SHAP","Data Visualization"], deliverables:["Property preprocessing and comparable-feature pipeline","Validated price model with error-band reporting","Interactive feature-importance and scenario view"] },
    { title:"Service Desk Ticket Auto-Routing", overview:"A transformer-based text classifier that reads incoming support requests and assigns them to the most relevant service team.", benefit:"Reduces triage time, shortens first-response delay and prevents tickets from bouncing through unrelated departments.", uniqueness:"Combines semantic classification with confidence-based fallback so uncertain requests can be reviewed rather than silently misrouted.", stack:["BERT","Transformers","NLP","REST API"], deliverables:["Ticket cleaning and label-taxonomy workflow","Fine-tuned routing classifier with confidence gates","Inference API and routing-performance dashboard"] },
    { title:"E-Commerce Recommendation Engine", overview:"A personalized ranking engine that uses purchase behavior and user-item similarity to recommend relevant products.", benefit:"Improves discovery, increases cross-sell opportunities and reduces the effort required to navigate a large catalog.", uniqueness:"Blends collaborative signals with popularity fallbacks to handle both established users and cold-start sessions.", stack:["Collaborative Filtering","Matrix Factorization","Python","Ranking Metrics"], deliverables:["User-item interaction and feedback pipeline","Recommendation model with cold-start strategy","Top-N service with offline ranking evaluation"] },
    { title:"Spam & Phishing Classifier", overview:"A lightweight message-security model that analyzes email or SMS content and flags likely spam or phishing attempts with low inference latency.", benefit:"Filters malicious communication earlier while keeping false positives visible and measurable.", uniqueness:"Treats precision, recall and threshold selection as product decisions, not merely a final accuracy score.", stack:["Naive Bayes","TF-IDF","NLP","Precision / Recall"], deliverables:["Text normalization and feature extraction pipeline","Low-latency classifier with tuned decision threshold","Threat explanation and evaluation report"] },
    { title:"Time-Series Demand Forecasting", overview:"A forecasting system that predicts product demand over the next 30–90 days using historical sales, trends and recurring seasonal behavior.", benefit:"Supports more accurate purchasing, reduces stockouts and limits excess inventory tied up in slow-moving products.", uniqueness:"Compares classical and additive models while preserving seasonality and uncertainty bands for operational planning.", stack:["ARIMA","Prophet","Time Series","Python"], deliverables:["Time-indexed cleaning and missing-period recovery","Backtested multi-horizon forecasting models","Inventory planning dashboard with confidence intervals"] },
    { title:"Customer Segmentation Dashboard", overview:"An unsupervised analytics system that groups customers by purchasing behavior, frequency and value, then turns clusters into usable profiles.", benefit:"Gives marketing and product teams clearer audiences for campaigns, offers and lifecycle communication.", uniqueness:"Combines PCA visualization with business-readable cluster narratives so the result is actionable beyond a notebook.", stack:["K-Means","PCA","Clustering","Dashboard"], deliverables:["Behavioral feature engineering and normalization","Cluster selection and stability evaluation","Interactive segment explorer with campaign guidance"] },
  ],
  "FULL STACK": [
    { title:"Collaborative Task Management", overview:"A Trello-style workspace with authenticated teams, drag-and-drop boards and real-time updates across connected clients.", benefit:"Keeps distributed teams synchronized without requiring refreshes or duplicating task state.", uniqueness:"Uses event-driven synchronization with optimistic UI behavior and server-side authorization for every board mutation.", stack:["React","Node.js","Socket.io","Authentication"], deliverables:["Workspace, board and task domain model","Real-time collaboration and presence events","Role-aware authentication and responsive UI"] },
    { title:"E-Commerce Platform", overview:"A complete digital storefront covering product discovery, cart management, user profiles, checkout and payment confirmation.", benefit:"Provides a production-shaped commerce flow that can convert browsing into secure, traceable orders.", uniqueness:"Treats payment state as a backend workflow with webhook verification rather than trusting the browser after checkout.", stack:["MERN","Stripe","REST APIs","Payment Webhooks"], deliverables:["Catalog, search, cart and account experiences","Secure checkout and verified payment lifecycle","Order management and transaction history"] },
    { title:"Automated Resume Screening", overview:"An HR portal that accepts bulk PDF resumes, extracts candidate evidence and ranks profiles against a supplied job description.", benefit:"Reduces repetitive first-pass review while keeping supporting skills and matched text visible to the recruiter.", uniqueness:"Pairs ranking with transparent evidence and keeps humans in control instead of presenting an opaque automatic rejection system.", stack:["React","REST API","PDF Parsing","NLP"], deliverables:["Secure multi-file upload and parsing pipeline","Job-to-candidate relevance scoring engine","Evidence-led recruiter ranking interface"] },
    { title:"Weather & Logistics Dashboard", overview:"A real-time operations dashboard that combines route information with external weather feeds to surface disruption risk.", benefit:"Helps logistics teams identify weather-related delays earlier and prioritize routes requiring intervention.", uniqueness:"Converts raw forecast data into route-specific operational alerts rather than presenting a generic weather screen.", stack:["React","Weather APIs","D3.js","Alerting"], deliverables:["External weather ingestion and caching layer","Route-risk rules and severity calculation","Live map, trend charts and alert dashboard"] },
    { title:"Interactive Learning Platform", overview:"A learning portal supporting hosted course video, lesson progress, quizzes and immediate grading feedback.", benefit:"Creates one consistent experience for delivering content, tracking completion and measuring understanding.", uniqueness:"Connects streaming events, progress persistence and assessment state so learners can resume reliably across devices.", stack:["React","Node.js","Database Design","Video Streaming"], deliverables:["Course, lesson and enrollment data model","Resumable video progress and completion tracking","Quiz engine with grading and learner analytics"] },
    { title:"Patient Health Record System", overview:"A secure portal where doctors and patients access appropriate medical records through explicit role-based permissions.", benefit:"Improves record availability while limiting sensitive information to authorized users and actions.", uniqueness:"Builds authorization, auditability and encryption into the domain model instead of adding security after the interface is complete.", stack:["RBAC","Encryption","Audit Logs","Secure APIs"], deliverables:["Doctor, patient and administrator access policies","Encrypted record storage and secure API layer","Audit trail and consent-aware record interface"] },
    { title:"Personal Finance API Service", overview:"A backend service for recording expenses, categorizing transactions and producing reliable monthly financial summaries.", benefit:"Creates a clean foundation that web, mobile or AI advisory clients can use without duplicating finance logic.", uniqueness:"Separates immutable transaction records from derived summaries and exposes consistent, versioned endpoints.", stack:["Express.js","MongoDB","API Design","Validation"], deliverables:["Authenticated transaction and category endpoints","Monthly aggregation and spending-summary engine","Validation, error handling and API documentation"] },
  ],
};
